"""
Django settings for site1 project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Xác định đường dẫn gốc của dự án
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'django-insecure-5z#k8^pj9q!v2m$x7n%h3r&y4t_l0u*o1e@w6b+jf'

# -------------------------------
# Cấu hình Static Files (CSS, JS, Images)
# -------------------------------

# Đường dẫn URL dùng để truy cập file tĩnh (các file như CSS, JS)
STATIC_URL = '/static/'

# Thư mục chứa các file tĩnh trong quá trình phát triển
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'home/static'),  # Thư mục chứa file tĩnh của app "home"
]

# Nơi thu thập file tĩnh khi chạy `collectstatic` (chỉ dùng khi deploy)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# -------------------------------
# Cấu hình Media Files (Hình ảnh upload)
# -------------------------------

# Đường dẫn URL để truy cập file media (hình ảnh tải lên)
MEDIA_URL = '/media/'

# Thư mục chứa các file media tải lên
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# -------------------------------
# Cấu hình chung
# -------------------------------

DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost' , '*']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'site1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "home/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'site1.wsgi.application'

# -------------------------------
# Cấu hình Database (SQLite)
# -------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -------------------------------
# Cấu hình Password
# -------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# -------------------------------
# Cấu hình Ngôn ngữ và Múi giờ
# -------------------------------
LANGUAGE_CODE = 'vi'  # Đổi sang tiếng Việt nếu muốn
TIME_ZONE = 'Asia/Ho_Chi_Minh'  # Đặt múi giờ Việt Nam
USE_I18N = True
USE_TZ = True

# -------------------------------
# Cấu hình Primary Key
# -------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}